** LINEAR ALGEBRA **

In [1]:
import numpy as np

In [6]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),69)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[69 69]
 [69 69]
 [69 69]]


array([[207., 207.],
       [207., 207.]])

In [10]:
# Determinent
c = np.identity(3)
np.linalg.det(c)

In [12]:
# Stats
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.min(stats)

np.int64(1)

In [ ]:
np.max(staticmethod)