**MATHEMATICS**

In [44]:
first = np.array([1,2,3,4])

In [46]:
print(first)

[1 2 3 4]


In [49]:
first + 2

array([3, 4, 5, 6])

In [51]:
first * 2 

array([2, 4, 6, 8])

In [52]:
first / 2

array([0.5, 1. , 1.5, 2. ])

In [53]:
first - 2

array([-1,  0,  1,  2])

In [66]:
second = np.array([5,4,6,3])
print(first+second)
print(second)

[6 6 9 7]
[5 4 6 3]


In [68]:
first ** 2

array([ 1,  4,  9, 16])

In [69]:
np.sin(first)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])