# **Initializing Data Types of Arrays**

In [9]:
import numpy as np

In [11]:
# All Zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# All ones matrix
np.ones((4,3,3),dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [19]:
# Any Other Values
np.full((2,2),90,dtype='int32')

array([[90, 90],
       [90, 90]], dtype=int32)

In [23]:
# Random Numbers
np.random.rand(4,2)

array([[0.84852608, 0.92707798],
       [0.78712653, 0.89597993],
       [0.98856716, 0.95439738],
       [0.85607265, 0.36036195]])

In [25]:
# random integer values
np.random.randint(7,size=(3,3))

array([[4, 3, 6],
       [1, 0, 0],
       [1, 3, 4]])

In [27]:
# Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
# Repeat array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,(3),axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [39]:
# QUESTION 1:
ones = np.ones((5,5))
print(ones)

zeros = np.zeros((3,3))
print(zeros)

zeros[1,1] = 9
print(zeros)

ones[1:4,1:4] = zeros
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Copy Arrays**

In [43]:
a = [1,2,3]
b = a.copy()

b[0] = 122
print(b)
print(a)

[122, 2, 3]
[1, 2, 3]
