In [27]:
# ** ARRAYS - 2 **
import numpy as np

In [12]:
a = np.array([[1,2,3,4,6,10,5],[1,2,3,4,5,18,5]])
print(a)

[[ 1  2  3  4  6 10  5]
 [ 1  2  3  4  5 18  5]]


In [13]:
a.shape

(2, 7)

In [14]:
# Get Specific Element (r,c)
a[1,5]


np.int64(18)

In [15]:
# Get Specific Element (r,c)
a[1,-2]

np.int64(18)

In [16]:
# Get specfic row
a[0,:]

array([ 1,  2,  3,  4,  6, 10,  5])

In [17]:
# Get specific column
a[:,5]

array([10, 18])

In [18]:
# [startIndex:endIndex:stepSize]
a[0,1:6:2]

array([ 2,  4, 10])

In [19]:
a[0,3] = 55
a

array([[ 1,  2,  3, 55,  6, 10,  5],
       [ 1,  2,  3,  4,  5, 18,  5]])

In [20]:
a[:,2] = 6
a

array([[ 1,  2,  6, 55,  6, 10,  5],
       [ 1,  2,  6,  4,  5, 18,  5]])

In [21]:
# 3d example
b = np.array([[[1,2],[3,4]],[[2,2],[5,5]]])
print(b)

[[[1 2]
  [3 4]]

 [[2 2]
  [5 5]]]


In [22]:
# Get specific element [matixNumber,rows,column]
b[0,1,1]

np.int64(4)

In [24]:
b[0,1,1]

np.int64(4)

In [25]:
b[:,1,:]

array([[3, 4],
       [5, 5]])