**Reorganizing Arrays**

In [2]:
import numpy as np

In [5]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print (before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [7]:
# Vertical Stacking
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

np.vstack([v1,v2])

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# Horizental stacking
h1 = np.ones((2,3))
h2 = np.zeros((2,2))

np.hstack